version: '2'

services:
  web:
    container_name: "app"
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/app/
      - /usr/app/node_modules
    command: node ./app.js
    #command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; node ./app.js'
    restart: on-failure
    depends_on:
      - postgres
      - elasticsearch

  postgres:
    container_name: "psqldb"
    build:
      context: .
      dockerfile: ./.docker/postgres/Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - .:/var/www/html
    working_dir: /var/www/html
    restart: always

  elasticsearch:
    container_name: "esdb"
    build:
      context: .
      dockerfile: ./.docker/elasticsearch/Dockerfile
    environment:
      - node.name=es-node
      - cluster.name=es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9200:9200"

volumes:
  postgres-data: {}
  es-data : {}
